
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: devsec
      POSTGRES_PASSWORD: devsec
      POSTGRES_DB: devsec_lab
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    image: node:20-alpine
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgres://devsec:devsec@postgres:5432/devsec_lab
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "4000:4000"
    command: ["sh", "-c", "apk add --no-cache docker-cli && npm install && node index.js"]

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    # volumes:
    #   - ./frontend:/usr/src/app
    depends_on:
      - backend

  juice-shop:
    image: bkimminich/juice-shop:latest
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
    restart: unless-stopped

  # Herramientas de seguridad
  semgrep:
    image: returntocorp/semgrep:latest
    volumes:
      - ./backend:/src
      - ./backend/results:/results
    working_dir: /src
    command: ["sleep", "infinity"]

  trivy:
    image: aquasec/trivy:latest
    volumes:
      - ./backend:/src
      - ./backend/results:/results
    working_dir: /src
    entrypoint: ["sh", "-c", "while true; do sleep 30; done"]

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/src
      - ./backend/results:/results
      - ./backend/results:/zap/wrk
    working_dir: /src
    command: ["sleep", "infinity"]

volumes:
  postgres_data:
  minio_data:
